### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by benhalverson** [ViennaRSS/viennarss.github.io#13]
@josh64x2 
Here's a link to my fork with the html and css files for the design we discussed.
https://github.com/benhalverson/viennarss.github.io/tree/newDesign
The files are under temp

**Comment by benhalverson** [comment]
oops looks like my branch wasn't pushed to github.

**Comment by josh64x2** [comment]
OK thanks :) I'll wait for the push and then take a look

**Comment by benhalverson** [comment]
I've updated the first comment with the correct link.

**Comment by josh64x2** [comment]
OK it is looking good :) I'll try to have a more in depth look on thursday.

**Comment by josh64x2** [comment]
@benhalverson can we please get a screenshot here of the front page design so that @barijaona can give his feedback?

Thanks :)

**Comment by benhalverson** [comment]
@josh64x2 @barijaona 
yep here are some screenshots of the home page
<img width="1440" alt="screen shot 2017-04-10 at 8 34 51 am" src="https://cloud.githubusercontent.com/assets/7907232/24869668/d51eb00a-1dc8-11e7-84db-2b7f40ef1d55.png">
![Uploading Screen Shot 2017-04-10 at 8.34.34 AM.png…]()
![Uploading Screen Shot 2017-04-10 at 8.34.20 AM.png…]()

**Comment by barijaona** [comment]
I am not a great expert at website design, but it seems fine to me

**Comment by josh64x2** [comment]
need:

- [ ] Screenshots of the UI
- [ ] Testimonials
- [ ] Any other text

**Comment by josh64x2** [comment]
Closed by #16
