### ISSUE TITLE
vienna-rss.com ?

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/viennarss.github.io#17]
Maintaining these Github.io pages in parallel of vienna-rss.com (hosted on Sourceforge) is tedious.

We should take a decision: do we switch vienna-rss.com to point here, and when ? If so, we should check all differences in content between the current website and viennarss.github.io

**Comment by josh64x2** [comment]
Sorry @barijaona i missed the notification about this.
Yes, it's tedious for sure. @benhalverson and I have very nearly finished PR #16 - Once we have, then we can remove the sourceforge site and I'll point the domain to github pages.

**Comment by josh64x2** [comment]
closed by #16
