### ISSUE TITLE
Fix mobile version of the website

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/viennarss.github.io#20]
Main issue is the logo doesn't seem to load on mobile:

![file](https://user-images.githubusercontent.com/799345/51889377-597b6580-2391-11e9-8933-a8ef013cf566.jpg)

**Comment by josh64x2** [comment]
@benhalverson one for you? :P

**Comment by benhalverson** [comment]
sure I'll take a stab at fixing this 👍
