### ISSUE TITLE
Update wording on about page 

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/viennarss.github.io#22]
https://www.vienna-rss.com/about is quite out of date - it refers to sourceforge hosting and Wordpress themes which we no longer use.

**Comment by josh64x2** [comment]
@Eitot and @takeanice do you want to be mentioned on this page? 😄

**Comment by benhalverson** [comment]
yes. I'd appreciate it! 👍

**Comment by TAKeanice** [comment]
Why not :) I would feel pressured to develop the browser replacement quicker, but that is a good thing :D
