### ISSUE TITLE
The blog section is outdated

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/viennarss.github.io#31]
Many articles that are listed at https://vienna-rss.sourceforge.io are missing from https://www.vienna-rss.com/blog

I don't know how to pull the content of these articles, as there is some redirection mechanism which prevents me from logging into the old Wordpress backend.
@josh64x2 , please !

**Comment by barijaona** [comment]
Related : #19 

There is no interest in setting any redirection of SourceForge pages, as the name servers are already pointing to the Github pages.

**Comment by josh64x2** [comment]
@barijaona the issue would be in the wordpress config - I'll have to try and login at some point this week and update the config.

**Comment by josh64x2** [comment]
@barijaona I've hardcoded the sourceforge URL into wordpress wp-config.php file. You should now be able to login without getting redirected!
