### ISSUE TITLE
Close the Vienna forum on Cocoaforge?

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/viennarss.github.io#42]
As mentioned in #41, the Cocoaforge forum causes some problems.

I propose to close the Vienna forum on Cocoaforge and add links to the GitHub page instead (e.g. in the forum description, in an announcement thread, maybe in some threads with recent activity). If needed, this could be done in several stages: announce it, disable the creation of new threads and finally close the forum.

Thoughts?

**Comment by josh64x2** [comment]
I've emailed the former domain holder to see if they are going to renew the domain or if they are willing to transfer to our control. Hopefully they reply, however it is probably time we migrate away from cocoaforge.com

**Comment by josh64x2** [comment]
The former domain holder had a misconfigured spam filter and didn't get any notifications from me nor from GoDaddy. Unfortunately the domain is now owned by some spam operation, so cocoaforge is dead.
